name = "nimbus-content-analyzer"
main = "worker-analyzer-openai.js"
compatibility_date = "2024-08-29"
account_id = "55987b6602e8ac9db46e14dcc7ad2c79"

# Environment variables (set these in Cloudflare dashboard or via CLI)
# OPENAI_API_KEY will be set as a secret via wrangler
