name = "nimbus-content-optimizer"
main = "worker-openai.js"
compatibility_date = "2024-08-29"

# Environment variables (set these in Cloudflare dashboard or via CLI)
# OPENAI_API_KEY = "your-openai-api-key-here"

[env.production]
name = "nimbus-content-optimizer-prod"

[env.staging]
name = "nimbus-content-optimizer-staging"

# Optional: Custom domain
# routes = [
#   "nimbus-ai.yourdomain.com/*"
# ]

# Optional: KV storage for caching
# kv_namespaces = [
#   { binding = "CACHE", id = "your-kv-namespace-id" }
# ]

# Optional: Rate limiting
# [limits]
# cpu_ms = 50000
