name = "nimbus-content-optimizer"
main = "worker-openai.js"
compatibility_date = "2024-08-29"
account_id = "55987b6602e8ac9db46e14dcc7ad2c79"

# Environment variables (set these in Cloudflare dashboard or via CLI)
# OPENAI_API_KEY will be set as a secret via wrangler

[env.production]
name = "nimbus-content-optimizer-prod"

[env.staging]
name = "nimbus-content-optimizer-staging"

# Optional: Custom domain
# routes = [
#   "nimbus-ai.yourdomain.com/*"
# ]

# V4.5: KV storage for AI result caching
kv_namespaces = [
  { binding = "NIMBUS_CACHE", id = "fc3d8474323a4256a3b65a36d4e6f6c6" }
]

# Optional: Rate limiting
# [limits]
# cpu_ms = 50000
